# AutomataCI - Project Configurations Data File
################################################################################
# WARNING: STRICTLY ONLY THIS PATTERN IS ALLOWED:                              #
#             'key' = 'value: string type' # 1 line tailing comment            #
#          Both Batch and POSIX Shell do not have sophisicated functions.      #
#          DO NOT go too creative with TOML!                                   #
################################################################################




####################
# PROJECT METADATA #
####################
# PROJECT_SKU
# This is the known product ID used as a command, marketing brand, etc.
# It should be used with dash ('-'), no space and no underscore for maximum
# compatibility.
PROJECT_SKU = "my-project"

# PROJECT_NAME
# This is the name of the product used in documentation, marketing addresses
# etc only. For programming purposes, PROJECT_SKU is used instead.
PROJECT_NAME = "My Project"

# PROJECT_VERSION
# This is to declare the current project's version. It can be used for
# generating version declaration files (e.g. VERSION, version.go, etc). You
# should only update this field and leave the AutomataCI to generate those
# output files.
PROJECT_VERSION = "0.0.1"




######################
# PROJECT FILESYSTEM #
######################
# PROJECT_PATH_ROOT
# This is an absolute pathing to locate the root directory of the project
# repository.
# PROJECT_PATH_ROOT = '...' # determined by ci.cmd automatically.


# PROJECT_PATH_AUTOMATA
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# AutomataCI working directory.
PROJECT_PATH_AUTOMATA = "automataCI"


# PROJECT_PATH_SOURCE
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's source codes working directory.
PROJECT_PATH_SOURCE = "srcPYTHON"


# PROJECT_PATH_TOOLS
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's tooling directory like programming languages' engine or executables.
PROJECT_PATH_TOOLS = "tools"


# PROJECT_PATH_BUILD
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's build output directory.
PROJECT_PATH_BUILD = "build"


# PROJECT_PATH_TEMP
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's temporary workspace directory.
PROJECT_PATH_TEMP = "tmp"


# PROJECT_PATH_LOG
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's log output directory.
PROJECT_PATH_LOG = "log"


# PROJECT_PATH_CI
# This is the relative pathing to PROJECT_PATH_ROOT + PROJECT_PATH_SOURCE where
# it locates the project's tech-specific CI job directory.
PROJECT_PATH_CI = ".ci"


# PROJECT_PATH_PKG
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's releasable packages output directory.
PROJECT_PATH_PKG = "pkg"




######################
# PYTHON TECHNOLOGY  #
######################
# PROJECT_PYTHON
# This is a reserved variable used in GitHub CI workflow where the GitHub CI
# will automatically determines the requirement for setting up python in the
# native OSes.
# PROJECT_PYTHON = '...' # Reserved - used in GitHub CI workflow.


# PROJECT_PATH_PYTHON_ENGINE
# This is a relative pathing to PROJECT_PATH_ROOT + PROJECT_PATH_TOOLS for
# setting up venv location.
PROJECT_PATH_PYTHON_ENGINE = "python-engine"
