# STRICTLY ONLY THIS PATTERN:
#             'key' = 'value: string type' # 1 line tailing comment
# Batch and POSIX does not have sophisicated toml parser. Do go too creative!




# PROJECT METADATA
PROJECT_SKU = "my-project"
PROJECT_NAME = "My Project"
PROJECT_VERSION = "0.0.1"




# PROJECT STRUCTURE
PROJECT_PATH_AUTOMATA = "automata" # relative to repository root
PROJECT_PATH_TOOLS = "tools" # relative to repository root
PROJECT_PATH_BUILD = "build" # relative to repository root
PROJECT_PATH_TEMP = "tmp" # relative to repository root
PROJECT_PATH_LOG = "log" # relative to repository root
PROJECT_PATH_SOURCE = "srcPYTHON" # relative to repository root
PROJECT_PATH_CI = ".ci" # relative to repository root
PROJECT_PATH_PKG = "pkg" # relative to repository root




# PYTHON PROJECT
# PROJECT_PYTHON = '...' # Reserved - used in GitHub CI workflow.

# venv location (engine)
PROJECT_PATH_PYTHON_ENGINE = "python-engine" #relative to repository root/PROJECT_PATH_TEMP
