# AutomataCI - Project Configurations Data File
################################################################################
# WARNING: STRICTLY ONLY THESE PATTERN ARE ALLOWED:                            #
#                                                                              #
#             'key' = 'value: string type' # 1 line tailing comment            #
#                                                                              #
#                                 OR                                           #
#                                                                              #
#             # full line comment                                              #
#                                                                              #
#          Both Batch and POSIX Shell do not have sophisicated functions       #
#          (e.g. POSIX Shell does not have array at all!).                     #
#                                                                              #
#          DO NOT get too creative with TOML!                                  #
################################################################################
####################
# PROJECT METADATA #
####################
# PROJECT_SKU
# This is the known product ID used as a command, marketing brand, etc.
# It should not be using dash ('-'), underscore ('_'), and space (' ') for
# maximum compatibility.
PROJECT_SKU = "automataci"


# PROJECT_APP_ID
# This is the known application complying to the unique 3-parts identifier
# (e.g. com.example.www) used in Flatpak, Google Play Store, etc. The triples
# must be a reversed domain with no dash ('-') and underscore ('_'). For GitHub
# projects, it's advisable to use 'io.github.[owner].[project]' format instead
# to avoid naming conflict.
PROJECT_APP_ID = "com.github.chewkeanho.automataci"


# PROJECT_NAME
# This is the name of the product used in documentation, marketing addresses
# etc only. For programming purposes, PROJECT_SKU is used instead.
PROJECT_NAME = "AutomataCI"


# PROJECT_PITCH
# A short elevator pitch about the project used as a short description. Max
# Max: 60 characters.
PROJECT_PITCH = "Solid Foundation for Kickstarting Your Software Development"


# PROJECT_VERSION
# This is to declare the current project's version. It can be used for
# generating version declaration files (e.g. VERSION, version.go, etc). You
# should only update this field and leave the AutomataCI to generate those
# output files.
#
# In case of a release with purpose like release candidates, tlide (~) is used
# like '0.0.1~rc1' instead of dashes (-). Some distribution ecosystem have
# strict and reserved rules for version sorting using dashes so tlide will be
# the best choice.
PROJECT_VERSION = "1.5.0"


# PROJECT_CADENCE
# The build cadence number usually to indicate the multiple builds of the same
# version like '12312' where some packager will generate the final version
# number as: '0.0.1-rc1-12312' or '0.0.1-12312'.
#
# When it doubt or unused, set to 1 and use numerical increment only.
PROJECT_CADENCE = "1"


# PROJECT_LICENSE
# The SPDX license tag. Refer https://spdx.org/licenses/ for finding or
# constructing your license identifier.
PROJECT_LICENSE = "Apache-2.0"


# PROJECT_SOURCE_URL
# The Project's source code URL. This URL points to the source code location.
# The URL can be used for other purposes such as The Docker's OCI Image source
# field (org.opencontainers.image.source) which can be used for other connecting
# purposes like GitHub Repo-Packages linking. See:
#     1. https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package
#
# Example:
#     1. GitHub Packages : https://github.com/OWNER/REPO
PROJECT_SOURCE_URL = "https://github.com/ChewKeanHo/AutomataCI"




######################
# PYTHON TECHNOLOGY  #
######################
# PROJECT_PYTHON
# This is a reserved variable used for enabling Python technology and also
# defining its source codes directory relative to PROJECT_PATH_ROOT.
# Depending on the offered service (e.g. GitHub CI), setting this
# variable with value shall notify the CI provider to setup Python development
# environment automatically.
#
# To enable it: simply supply the path (e.g. default is 'srcPYTHON').
# To disable it: simply supply an empty path (e.g. default is '').
PROJECT_PYTHON = 'srcPYTHON'


# PROJECT_PATH_PYTHON_ENGINE
# This is a relative pathing to PROJECT_PATH_ROOT + PROJECT_PATH_TOOLS for
# setting up venv location.
PROJECT_PATH_PYTHON_ENGINE = "python-engine"


# PROJECT_PYPI_REPO_URL
# The PyPi upstream repo to push the PyPi package. The defualt PyPi values are:
#     Test Zone : https://test.pypi.org/legacy/
#     Actual    : https://upload.pypi.org/legacy/
PROJECT_PYPI_REPO_URL = "https://test.pypi.org/legacy/"


# PROJECT_PYPI_README
# The PyPi README file relative to PROJECT_PATH_ROOT directory. Default is the
# the common README.md. Please use UNIX pathing (/) for sub-directories.
PROJECT_PYPI_README = "README.md"


# PROJECT_PYPI_README_MIME
# The PyPi README file relative to PROJECT_PATH_ROOT directory. Default is the
# the common README.md which is a 'text/markdown' MIME type.
PROJECT_PYPI_README_MIME = "text/markdown"




##########################
# DISTRIBUTION ECOSYSTEM #
##########################
# PROJECT_CONTACT_NAME
# Entity's full name for inquiries.
PROJECT_CONTACT_NAME = "Your Legal Full Name Here"


# PROJECT_CONTACT_EMAIL
# Entity's email channel for email communications.
PROJECT_CONTACT_EMAIL = "contact@youremail.example"


# PROJECT_CONTACT_WEBSITE
# Entity's website channel for sourcing information.
PROJECT_CONTACT_WEBSITE = "https://your-product.website.here"


# PROJECT_GPG_ID
# Your GPG ID for signing here. Note that this requires GPG to be installed in
# the system and the secret key is available for performing such transaction.
PROJECT_GPG_ID = "49B7878749107ED9C456267ACFD3316C29873FB5"


# PROJECT_CHANGELOG_TITLE
# The title of the changelog file.
PROJECT_CHANGELOG_TITLE = "Changelog | 更新日志 | Endringslogg | Cacatan Perubahan | Ändringslogg | 変更履歴"

# PROJECT_RELEASE_SHA256
# Perform SHA256 checksum file generation in Release job. To disable it, simply
# let it empty.
#
# Otherwise, as long as it's not empty, it is enabled.
PROJECT_RELEASE_SHA256 = "enabled"


# PROJECT_RELEASE_SHA512
# Perform SHA512 checksum file generation. To disable it, simply let it
# empty.
#
# Otherwise, as long as it's not empty, it is enabled.
PROJECT_RELEASE_SHA512 = "enabled"


# PROJECT_DEBIAN_IS_NATIVE
# Flag to determine the project is Debian natively sponsored package. Usually
# is false.
# Only accept: "true/false"
PROJECT_DEBIAN_IS_NATIVE = "false"


# PROJECT_DEBIAN_PRIORITY
# Indicate the current package's distribution priority. Strictly the following
# values
#  (1) required
#  (2) important
#  (3) standard
#  (4) optional
#  (5) extra
# see https://www.debian.org/doc/debian-policy/ch-archive.html#s-priorities for
# more info.
PROJECT_DEBIAN_PRIORITY = "optional"


# PROJECT_DEBIAN_DISTRIBUTION
# The distribution series for compiling the .deb pakage changelog. See this page
# for more info:
# https://www.debian.org/doc/debian-policy/ch-controlfields.html#id25
# https://www.debian.org/doc/debian-policy/ch-source.html#debian-changelog-debian-changelog
#
# Strictly of the following values:
#   (1) stable = for stable branches (e.g. 'main')
#   (2) unstable OR testing = for next release branches (e.g 'staging', or 'next').
#   (3) experimental = for latest branches (e.g 'experimental' or 'edge').
PROJECT_DEBIAN_DISTRIBUTION = "stable"


# PROJECT_DEBIAN_URGENCY
# The urgency value for compiling the .deb pakage changelog. See this page
# for more info:
# https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-urgency
# https://www.debian.org/doc/debian-policy/ch-source.html#debian-changelog-debian-changelog
#
# Strictly of the following values:
#   (1) low
#   (2) medium
#   (3) high           = for user diversions
#   (4) emergency
#   (5) critical
PROJECT_DEBIAN_URGENCY = "low"


# PROJECT_DEBIAN_SECTION
# The categories the project belongs to in the Debian .deb package ecosystem.
# Contains restricted values. Refer:
#      https://www.debian.org/doc/debian-policy/ch-archive.html#sections
# For maximum compliances
PROJECT_DEBIAN_SECTION="devel"


# PROJECT_FLATPAK_RUNTIME
# The runtime module where the Flatpak is operating on.
PROJECT_FLATPAK_RUNTIME="org.freedesktop.Platform"


# PROJECT_FLATPAK_RUNTIME_VERSION
# The runtime module where the Flatpak is operating on.
PROJECT_FLATPAK_RUNTIME_VERSION="22.08"


# PROJECT_FLATPAK_SDK
# The runtime module where the Flatpak is operating on.
PROJECT_FLATPAK_SDK="org.freedesktop.Sdk"


# PROJECT_REPREPRO_CODENAME
# The codename used by .deb's Reprepro for publishing any detected .deb package
# file. In any cases, the value **MUST** match any one of the 'Codename:' field
# defined in PROJECT_PATH_RESOURCES/publishers/deb/conf/distributions data list.
PROJECT_REPREPRO_CODENAME="main"


# PROJECT_STATIC_REPO
# The git repository for publishing all the packages using static file sharing
# (e.g. .deb repo, .rpm repo, flatpak repo, etc). This URL shall be git cloned
# as the PROJECT_PATH_RELEASE directory.
PROJECT_STATIC_REPO="git@github.com:ChewKeanHo/AutomataCI.wiki.git"


# PROJECT_STATIC_REPO_KEY
# The git upstream key. Default is 'origin'.
PROJECT_STATIC_REPO_KEY="origin"


# PROJECT_STATIC_REPO_BRANCH
# The git upstream branch. Default is 'master' or 'main'.
PROJECT_STATIC_REPO_BRANCH="master"


# PROJECT_STATIC_URL
# The public facing base URL for accessing the published static repo. This URL
# shall be used to construct the final user instructions across various
# distribution ecosystems.
PROJECT_STATIC_URL="https://github.com/ChewKeanHo/AutomataCI/wiki/"


# PROJECT_DOCKER_REGISTRY
# The Docker registry URI value. DO NOT end with a slash. Example:
#     1. DockerHub     : registry.hub.docker.com/[ NAMESPACE ]
#     2. GitHub Package: ghcr.io/[ NAMESPACE ]
#     2. Local         : localhost:5000/[ NAMESPACE ]
PROJECT_DOCKER_REGISTRY = "ghcr.io/chewkeanho"


# DOCKER_CLI_EXPERIMENTAL
# Enable the Docker's experimental CLI features for using buildx. If disabled,
# is shall break many of the CI job.
DOCKER_CLI_EXPERIMENTAL = "enabled"



######################
# PROJECT FILESYSTEM #
######################
# PROJECT_PATH_ROOT
# This is an absolute pathing to locate the root directory of the project
# repository.
# PROJECT_PATH_ROOT = '...' # Reserved - determined by ci.cmd automatically.


# PROJECT_PATH_AUTOMATA
# This is the reserved pathing to PROJECT_PATH_ROOT where it locates the
# AutomataCI working directory.
# PROJECT_PATH_AUTOMATA = "automataCI" # Reserved - determined by ci.cmd automatically.


# PROJECT_PATH_SOURCE
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# baseline source directory independent of technological section and acts as an
# overall controls.
PROJECT_PATH_SOURCE = "src"


# PROJECT_PATH_TOOLS
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's tooling directory like programming languages' engine or executables.
PROJECT_PATH_TOOLS = "tools"


# PROJECT_PATH_BUILD
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's build output directory.
PROJECT_PATH_BUILD = "build"


# PROJECT_PATH_TEMP
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's temporary workspace directory.
PROJECT_PATH_TEMP = "tmp"


# PROJECT_PATH_LOG
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's log output directory.
PROJECT_PATH_LOG = "log"


# PROJECT_PATH_CI
# This is the relative pathing to PROJECT_PATH_ROOT + PROJECT_PATH_SOURCE where
# it locates the project's tech-specific CI job directory.
PROJECT_PATH_CI = ".ci"


# PROJECT_PATH_PKG
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's releasable packages output directory.
PROJECT_PATH_PKG = "pkg"


# PROJECT_PATH_RELEASE
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's publication output directory.
PROJECT_PATH_RELEASE = "releases"


# PROJECT_PATH_DOCS
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's documentation directory.
PROJECT_PATH_DOCS = "public"


# PROJECT_PATH_RESOURCES
# This is the relative pathing to PROJECT_PATH_ROOT where it locates the
# project's main non-code generative materials directory.
PROJECT_PATH_RESOURCES = "resources"
