name: "Enhance A Feature"
description: "To request a feature enhancement for the project."
labels: [ "Enhancement", "Discussion" ]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >
        Please provide a short description of what you're looking forward to
        enhance or remove. Please include the story behind the idea to better
        visualize your case.
      placeholder: "E.g: 15cm long pencil instead of 5cm - used up too quickly."
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected Behavior
      description: >
        Please specify the expected behavior below.
      placeholder: "E.g: Pencil is at least 15cm longer."
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: >
        Please specify the current behavior below.
      placeholder: "E.g: Pencil is 5cm long and used up in 30 seconds."
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Associated Data Files
      description: >
        Please drag and drop all the necessary data files (e.g. screenshot,
        logs, etc) into the box below. Each successful uploads shall render an
        URL link on its own.
      placeholder: "Please drag and drop it here."
    validations:
      required: false
