# Copyright 2023  (Holloway) Chew, Kean Ho <hollowaykeanho@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at:
#                 http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
. "${env:PROJECT_PATH_ROOT}\${env:PROJECT_PATH_AUTOMATA}\services\io\fs.ps1"




function CITATION-Build {
	param(
		[string]$__filepath,
		[string]$__abstract_filepath,
		[string]$__citation_filepath,
		[string]$__cff_version,
		[string]$__type,
		[string]$__date,
		[string]$__title,
		[string]$__version,
		[string]$__license,
		[string]$__repo,
		[string]$__repo_code,
		[string]$__repo_artifact,
		[string]$__contact_name,
		[string]$__contact_website,
		[string]$__contact_email
	)


	# validate input
	if ([string]::IsNullOrEmpty($__cff_version)) {
		return 0 # requested to be disabled
	}

	if ([string]::IsNullOrEmpty($__filepath) -or
		[string]::IsNullOrEmpty($__title) -or
		[string]::IsNullOrEmpty($__type)) {
		return 1
	}

	if ([string]::IsNullOrEmpty($__citation_filepath) -or
		(-not (Test-Path -Path "${__citation_filepath}"))) {
		return 1
	}


	# execute
	$null = FS-Remove-Silently "${__filepath}"
	$null = FS-Make-Housing-Directory "${__filepath}"
	$__process = FS-Write-File "${__filepath}" @"
# WARNING: auto-generated by AutomataCI

cff-version: `"${__cff_version}`"
type: `"${__type}`"
"@
	if ($__process -ne 0) {
		return 1
	}

	## date
	if (-not [string]::IsNullOrEmpty($__date)) {
		$__process = FS-Append-File "${__filepath}" @"
date-released: `"${__date}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## title
	if (-not [string]::IsNullOrEmpty($__title)) {
		$__process = FS-Append-File "${__filepath}" @"
title: `"${__title}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## version
	if (-not [string]::IsNullOrEmpty($__version)) {
		$__process = FS-Append-File "${__filepath}" @"
version: `"${__version}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## license
	if (-not [string]::IsNullOrEmpty($__license)) {
		$__process = FS-Append-File "${__filepath}" @"
license: `"${__license}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## repository
	if (-not [string]::IsNullOrEmpty($__repo)) {
		$__process = FS-Append-File "${__filepath}" @"
repository: `"${__repo}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## repository-code
	if (-not [string]::IsNullOrEmpty($__repo_code)) {
		$__process = FS-Append-File "${__filepath}" @"
repository-code: `"${__repo_code}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## repository-artifact
	if (-not [string]::IsNullOrEmpty($__version)) {
		$__process = FS-Append-File "${__filepath}" @"
repository-artifact: `"${__repo_artifact}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## url
	if (-not [string]::IsNullOrEmpty($__contact_website)) {
		$__process = FS-Append-File "${__filepath}" @"
url: `"${__contact_website}`"
"@
		if ($__process -ne 0) {
			return 1
		}
	}

	## contact
	if ((-not [string]::IsNullOrEmpty($__contact_name)) -and
		((-not [string]::IsNullOrEmpty($__contact_website)) -or
		(-not [string]::IsNullOrEmpty($__contact_email)))) {
		$__process = FS-Append-File "${__filepath}" @"
contact:
  - affiliation: `"${__contact_name}`"
"@
		if ($__process -ne 0) {
			return 1
		}

		if (-not [string]::IsNullOrEmpty($__contact_email)) {
			$__process = FS-Append-File "${__filepath}" @"
    email: `"${__contact_email}`"
"@
			if ($__process -ne 0) {
				return 1
			}
		}

		if (-not [string]::IsNullOrEmpty($__contact_website)) {
			$__process = FS-Append-File "${__filepath}" @"
    website: `"${__contact_website}`"
"@
			if ($__process -ne 0) {
				return 1
			}
		}
	}

	## abstract
	if (Test-Path -Path "${__abstract_filepath}") {
		$__process = FS-Append-File "${__filepath}" @"
abstract: |-
"@
		if ($__process -ne 0) {
			return 1
		}

		foreach ($__line in (Get-Content "${__abstract_filepath}")) {
			if ((-not [string]::IsNullOrEmpty($__line)) -and
				[string]::IsNullOrEmpty($__line -replace "#.*$")) {
				continue
			}

			$__line = $__line -replace '#.*'
			if (-not [string]::IsNullOrEmpty($__line)) {
				$__line = "  ${__line}"
			}

			$__process = FS-Append-File "${__filepath}" "${__line}"
			if ($__process -ne 0) {
				return 1
			}
		}
	}

	## other citations
	foreach ($__line in (Get-Content "${__citation_filepath}")) {
		if ((-not [string]::IsNullOrEmpty($__line)) -and
			[string]::IsNullOrEmpty($__line -replace "#.*$")) {
			continue
		}

		$__line = $__line -replace '#.*'
		if ([string]::IsNullOrEmpty($__line)) {
			continue
		}

		$__process = FS-Append-File "${__filepath}" "${__line}"
		if ($__process -ne 0) {
			return 1
		}
	}


	# report status
	return 0
}
