name: GitHub CI on Push
run-name: Run the repo development process across all OSes for main & next/staging/testing branches.
on:
  push:
    branches: [ main, staging, next, testing ]
jobs:
  run-on-linux-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: . ./ci.cmd setup
      - run: . ./ci.cmd start
      - run: . ./ci.cmd prepare
      - run: . ./ci.cmd test
      - run: . ./ci.cmd build
      - run: . ./ci.cmd compose
  run-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\ci.cmd setup
      - run: .\ci.cmd start
      - run: .\ci.cmd prepare
      - run: .\ci.cmd test
      - run: .\ci.cmd build
      - run: .\ci.cmd compose
  run-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: . ./ci.cmd setup
      - run: . ./ci.cmd start
      - run: . ./ci.cmd prepare
      - run: . ./ci.cmd test
      - run: . ./ci.cmd build
      - run: . ./ci.cmd compose
